jwt:
  key: ${JWT_KEY}

spring:
  application:
    name: UserInterfaceEndpoint

  main:
    allow-bean-definition-overriding: true
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5433/main_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${OPEN_AI}
      chat:
        options:
          model: gpt-4.1
          temperature: 0.4

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        type: SYNC
        request-timeout: 60s
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse:
          connections:
            server1:
              url: http://localhost:8081
            server2:
              url: http://localhost:8082

logging:
  level:
    io.modelcontextprotocol: TRACE
    org.springframework.ai.mcp: TRACE
