jwt:
  key: weuifgwuiofghhuwhwi1234567890jhwbfrbjkwfbvbvbjsfvbsvbdjkdbvjkdbvbjv

spring:
  ai:
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 60s
        type: SYNC
        sse:
          connections:
            server1:
              url: http://localhost:8081
            server2:
              url: http://localhost:8082