version: '3.8'

services:
  pgvector-car:
    image: pgvector/pgvector:pg17
    container_name: car-detail-pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  pgvector-car-booking:
    image: pgvector/pgvector:pg17
    container_name: car-booking-pg
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_booking_db
    volumes:
      - car_booking:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
  car_booking:
