spring:
  application:
    name: CarBooking
  main:
    allow-bean-definition-overriding: true
    banner-mode: off

  datasource:
    driver-class-name: com.sap.db.jdbc.Driver
    url: ${HANA_URL}
    username: ${HANA_DATASOURCE_USERNAME}
    password: ${HANA_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  ai:
    openai:
      api-key: ${OPEN_AI}
      chat:
        options:
          model: gpt-4.1
          temperature: 0.5

    vectorstore:
      hanadb:
        tableName: BOOKING_EMBED
        topK: 9

    mcp:
      server:
        name: car-details
        version: 1.0.0
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message
        type: SYNC
        instruction: "The server does booking of cars"
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: true

server:
  port: 8082
